name: Build PdfImageAddIn

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '16.0'
    
    - name: Download PDFium
      run: |
        # Скачиваем предсобранные PDFium библиотеки с retry логикой
        $url = "https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F5790/pdfium-win-x86.tgz"
        $output = "pdfium-win-x86.tgz"
        $maxAttempts = 3
        $attempt = 1
        
        while ($attempt -le $maxAttempts) {
            try {
                Write-Host "Попытка $attempt из $maxAttempts загрузки PDFium..."
                
                # Пробуем curl (более надежный для больших файлов)
                if (Get-Command curl -ErrorAction SilentlyContinue) {
                    Write-Host "Используем curl для загрузки..."
                    & curl -L -o $output $url --retry 3 --retry-delay 5 --max-time 300
                    if ($LASTEXITCODE -eq 0) {
                        Write-Host "✅ Загрузка через curl успешна"
                        break
                    }
                }
                
                # Fallback на Invoke-WebRequest
                Write-Host "Используем Invoke-WebRequest..."
                $webClient = New-Object System.Net.WebClient
                $webClient.DownloadFile($url, $output)
                Write-Host "✅ Загрузка через WebClient успешна"
                break
                
            } catch {
                Write-Host "❌ Попытка $attempt не удалась: $($_.Exception.Message)"
                if ($attempt -eq $maxAttempts) {
                    Write-Host "🔄 Пробуем альтернативный источник..."
                    # Используем альтернативный URL с GitHub releases
                    $altUrl = "https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-win-x86.tgz"
                    try {
                        & curl -L -o $output $altUrl --retry 3 --retry-delay 5 --max-time 300
                        if ($LASTEXITCODE -eq 0) {
                            Write-Host "✅ Загрузка из альтернативного источника успешна"
                            break
                        }
                    } catch {
                        Write-Host "❌ Все попытки загрузки не удались"
                        throw "Не удалось загрузить PDFium библиотеки"
                    }
                }
                $attempt++
                Start-Sleep -Seconds 10
            }
        }
        
        # Проверяем что файл загружен
        if (!(Test-Path $output)) {
            throw "Файл PDFium не был загружен"
        }
        
        Write-Host "📦 Распаковка PDFium..."
        tar -xzf $output
        
        # Создаем директории для библиотек
        New-Item -ItemType Directory -Path "lib" -Force
        New-Item -ItemType Directory -Path "include" -Force
        
        # Копируем файлы
        Write-Host "📂 Копирование файлов..."
        if (Test-Path "bin") {
            Copy-Item -Path "bin\*.dll" -Destination "lib\" -Force
        }
        if (Test-Path "lib") {
            Copy-Item -Path "lib\*.lib" -Destination "lib\" -Force
        }
        if (Test-Path "include") {
            Copy-Item -Path "include\*" -Destination "include\" -Recurse -Force
        }
        
        # Показываем структуру
        Write-Host "📋 Результат установки PDFium:"
        Get-ChildItem -Path "lib" -Recurse
        Get-ChildItem -Path "include" -Recurse
      shell: powershell
    
    - name: Build AddIn Base Library
      run: |
        cd Source/Addin
        # Компилируем базовую библиотеку
        cl /c /EHsc /I../../include *.cpp
        lib /OUT:../../lib/addin.lib *.obj
      shell: cmd
    
    - name: Build PdfImageAddIn
      run: |
        cd Source/PdfImageAddIn
        
        # Компилируем исходные файлы
        cl /c /EHsc /I../../include /I../Addin /DWIN32 /D_WINDOWS /D_USRDLL /D_WINDLL PdfImageAddIn.cpp MyClassFactory.cpp PdfDragDropWindow.cpp
        
        # Создаем DLL
        link /DLL /OUT:PdfImageAddIn.dll /DEF:PdfImageAddIn.def PdfImageAddIn.obj MyClassFactory.obj PdfDragDropWindow.obj ../../lib/addin.lib ../../lib/pdfium.lib ole32.lib oleaut32.lib uuid.lib
        
        # Проверяем результат
        if (Test-Path "PdfImageAddIn.dll") {
          Write-Host "✅ PdfImageAddIn.dll успешно создан"
          Get-Item "PdfImageAddIn.dll" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "❌ Ошибка создания PdfImageAddIn.dll"
          exit 1
        }
      shell: powershell
    
    - name: Build LogAddIn (дополнительно)
      run: |
        cd Source/LogAddin
        
        # Компилируем LogAddIn
        cl /c /EHsc /I../Addin /DWIN32 /D_WINDOWS /D_USRDLL /D_WINDLL LogAddIn.cpp MyClassFactory.cpp
        
        # Создаем DLL
        link /DLL /OUT:LogAddIn.dll /DEF:ADDIN.DEF LogAddIn.obj MyClassFactory.obj ../../lib/addin.lib ole32.lib oleaut32.lib uuid.lib
        
        if (Test-Path "LogAddIn.dll") {
          Write-Host "✅ LogAddIn.dll успешно создан"
        }
      shell: powershell
    
    - name: Build ScanSymb (дополнительно)
      run: |
        cd Source/ScanSymb
        
        # Компилируем ScanSymb
        cl /c /EHsc /I../Addin /DWIN32 /D_WINDOWS /D_USRDLL /D_WINDLL ScanAddIn.cpp MyClassFactory.cpp ScanWindow.cpp
        
        # Создаем DLL
        link /DLL /OUT:ScanSymb.dll /DEF:ScanSymb.DEF ScanAddIn.obj MyClassFactory.obj ScanWindow.obj ../../lib/addin.lib ole32.lib oleaut32.lib uuid.lib user32.lib
        
        if (Test-Path "ScanSymb.dll") {
          Write-Host "✅ ScanSymb.dll успешно создан"
        }
      shell: powershell
    
    - name: Copy artifacts
      run: |
        # Создаем папку для артефактов
        New-Item -ItemType Directory -Path "artifacts" -Force
        
        # Копируем собранные DLL
        if (Test-Path "Source/PdfImageAddIn/PdfImageAddIn.dll") {
          Copy-Item -Path "Source/PdfImageAddIn/PdfImageAddIn.dll" -Destination "artifacts/"
        }
        if (Test-Path "Source/LogAddin/LogAddIn.dll") {
          Copy-Item -Path "Source/LogAddin/LogAddIn.dll" -Destination "artifacts/"
        }
        if (Test-Path "Source/ScanSymb/ScanSymb.dll") {
          Copy-Item -Path "Source/ScanSymb/ScanSymb.dll" -Destination "artifacts/"
        }
        
        # Копируем документацию
        Copy-Item -Path "*.htm" -Destination "artifacts/" -Force
        Copy-Item -Path "Source/PdfImageAddIn/README.md" -Destination "artifacts/" -Force
        Copy-Item -Path "Source/PdfImageAddIn/PDFIUM_INSTALL.md" -Destination "artifacts/" -Force
        Copy-Item -Path "Source/PdfImageAddIn/PdfImageComp.htm" -Destination "artifacts/" -Force
        
        # Показываем что получилось
        Get-ChildItem -Path "artifacts" -Recurse
      shell: powershell
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-components
        path: artifacts/
        retention-days: 30
    
    - name: Test basic functionality
      run: |
        # Простейший тест - проверяем что DLL можно загрузить
        try {
          $dll = [System.Reflection.Assembly]::LoadFile("$PWD\artifacts\PdfImageAddIn.dll")
          Write-Host "✅ PdfImageAddIn.dll загружается корректно"
        } catch {
          Write-Host "⚠️ Предупреждение: Не удалось загрузить DLL напрямую (возможно, требуются зависимости)"
        }
      shell: powershell
      continue-on-error: true 